name: "Deploy Azure Key Vault"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        #run: az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
        run: az login --service-principal -u $ARM_CLIENT_ID -p 1RRiverniger. --tenant $ARM_TENANT_ID
        
        # uses: azure/login@v1
        # with:
        #     creds: |
        #       {

        #       "ARM_CLIENT_ID": "${{ secrets.ARM_CLIENT_ID }}",
        #       "ARM_CLIENT_SECRET": "${{ secrets.ARM_CLIENT_SECRET }}",
        #       "ARM_TENANT_ID": "${{ secrets.ARM_TENANT_ID }}",
        #       "ARM_SUBSCRIPTION_ID": "${{ secrets.ARM_SUBSCRIPTION_ID}}"

        #       }

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
