name: "Deploy Azure Key Vault"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    # env:
      # ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      # ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      # ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      # ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        # run: az login --service-principal -u "${{ secrets.ARM_CLIENT_ID }}" -p "${{ secrets.ARM_CLIENT_SECRET }}" --tenant $ARM_TENANT_ID
        run: az login --service-principal -u "uyi" -p "1RRiverniger." --tenant 3cc0f970-a306-44bf-aa7e-b66c4337d0ae         #$ARM_TENANT_ID

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        # with:
        #   terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
